name: Setup Sidecar for Integration Tests

on:
  workflow-dispatch

jobs:
  build-and-deploy:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # service/sidecar container for azure-sql-edge
    services:
      mssql:
        image: mcr.microsoft.com/azure-sql-edge:latest
        env:
          ACCEPT_EULA: 1
          SA_PASSWORD: P@ssw0rd
        ports:
          - 1433:1433
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'wait for sql to be ready'
        run: |
          set +o pipefail +e
          for i in {1..60};
          do
            sqlcmd -S localhost -U sa -P P@ssw0rd -d master -Q "select getdate()"
            if [ $? -eq 0 ]
            then
              echo "sql server ready"
            else
              echo " not ready yet..."
              sleep 1
            fi
          done
          set -o pipefail -e
        
      - uses: azure/sql-action@v1.3
        with:
          connection-string: "Server=localhost:Initial Catalog=DevOpsForAzureSQL;User ID=sa;Password=P@ssw0rd;" # the local connection string
          project-file: './database/DevOpsForAzureSQL.Database/DevOpsForAzureSQL.Database.sqlproj' # the SQLproj file
      
      - name: run a query
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d DevOpsForAzureSQL -Q "SELECT Id, City, FirstName, LastName FROM dbo.Customers for json auto"
